### ISSUE TITLE
Merge the final updates from PhiloGL

### ISSUE THREAD

**Issue by ibgreen** [uber-common/luma.gl#1]
@wwwtyro A couple of your PhiloGL PRs happened after we forked, we need to get your changes moved over asap

**Comment by wwwtyro** [comment]
@ibgreen sounds good I'll put in some PR's tonight. :+1:

**Comment by wwwtyro** [comment]
This can be closed.

**Comment by ibgreen** [comment]
Closed by https://github.com/uber-common/luma.gl/pull/12
