### ISSUE TITLE
Lesson 14/15 Console warnings

### ISSUE THREAD

**Issue by ibgreen** [uber-common/luma.gl#36]
@wwwtyro 
256(index):1 [GroupMarkerNotSet(crbug.com/242999)!:D0AC894CA37F0000]PERFORMANCE WARNING: Attribute 0 is disabled. This has signficant performance penalty
(index):1 WebGL: too many errors, no more errors will be reported to the console for this context.

**Comment by wwwtyro** [comment]
@ibgreen Not sure if recent changes fixed this or what, but I'm not currently seeing any errors for these lessons. I _did_ find an error in lesson 13, and have patched it in https://github.com/uber-common/luma.gl/pull/42

**Comment by ibgreen** [comment]
OK, I added code to unset attributes after using a program in model.js to avoid the dreaded GroupMarker warning issue for deck.gl (per your discussion with @philogb), that probably took care of this too. Closing for now.
